module.exports = {
  CI: require('./CI'),
  BusinessService: require('./BusinessService'),
  SecurityIncident: require('./SecurityIncident'),
  Vulnerability: require('./Vulnerability'),
  RiskItem: require('./RiskItem'),
  Control: require('./Control'),
  PolicyDocument: require('./PolicyDocument'),
  AuditEngagement: require('./AuditEngagement'),
  ThirdParty: require('./ThirdParty'),
  ContinuityPlan: require('./ContinuityPlan'),
  Building: require('./Building'),
  Space: require('./Space'),
  Reservation: require('./Reservation'),
  Visitor: require('./Visitor'),
  MoveRequest: require('./MoveRequest'),
  WorkplaceCase: require('./WorkplaceCase'),
  LegalMatter: require('./LegalMatter'),
  ContractLifecycle: require('./ContractLifecycle'),
  Supplier: require('./Supplier'),
  Requisition: require('./Requisition'),
  SourcingEvent: require('./SourcingEvent'),
  FinanceCase: require('./FinanceCase'),
  CloseTask: require('./CloseTask'),
  EsgMetric: require('./EsgMetric'),
  EmissionFactor: require('./EmissionFactor'),
};
