const { Schema, model } = require("mongoose");
const AppointmentSchema = new Schema(
  {
    tenantId: {
      type: Schema.Types.ObjectId,
      ref: "Tenant",
      required: true,
      index: true,
    },
    locationId: {
      type: Schema.Types.ObjectId,
      ref: "WalkupLocation",
      required: true,
      index: true,
    },
    serviceId: {
      type: Schema.Types.ObjectId,
      ref: "WalkupService",
      required: true,
      index: true,
    },
    queueId: { type: Schema.Types.ObjectId, ref: "WalkupQueue" },
    number: { type: String, required: true, unique: true },
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    userName: { type: String, required: true, trim: true },
    userEmail: { type: String, trim: true, default: "" },
    userPhone: { type: String, trim: true, default: "" },
    scheduledAt: { type: Date, required: true, index: true },
    durationMinutes: { type: Number, default: 15 },
    status: {
      type: String,
      enum: [
        "scheduled",
        "confirmed",
        "checked_in",
        "in_service",
        "completed",
        "no_show",
        "cancelled",
        "rescheduled",
      ],
      default: "scheduled",
      index: true,
    },
    checkinMethod: { type: String, enum: ["kiosk", "mobile", "desk", "qr"] },
    reminderSent: { type: Boolean, default: false },
    reminderSentAt: { type: Date },
    checkinAt: { type: Date },
    startedAt: { type: Date },
    completedAt: { type: Date },
    technicianId: { type: Schema.Types.ObjectId, ref: "User" },
    technicianName: { type: String, trim: true, default: "" },
    reason: { type: String, trim: true, default: "" },
    notes: { type: String, trim: true, default: "" },
    outcome: {
      type: String,
      enum: ["resolved", "escalated", "deferred", "no_show", "cancelled"],
      default: "resolved",
    },
    ticketId: { type: Schema.Types.ObjectId, ref: "Ticket" },
    incidentId: { type: Schema.Types.ObjectId, ref: "Incident" },
    requestId: { type: Schema.Types.ObjectId, ref: "Request" },
    metadata: { type: Schema.Types.Mixed, default: {} },
    createdBy: { type: Schema.Types.ObjectId, ref: "User" },
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date },
    deletedBy: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true },
);
AppointmentSchema.index({
  tenantId: 1,
  locationId: 1,
  scheduledAt: 1,
  status: 1,
});
AppointmentSchema.index({ tenantId: 1, userId: 1, status: 1 });
module.exports = model("Appointment", AppointmentSchema);
