const { Schema, model } = require("mongoose");
const DependencySchema = new Schema(
  {
    tenantId: {
      type: Schema.Types.ObjectId,
      ref: "Tenant",
      required: true,
      index: true,
    },
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true, default: "" },
    number: { type: String, required: true, unique: true },
    sourceType: {
      type: String,
      enum: [
        "ci",
        "service",
        "application",
        "database",
        "server",
        "network",
        "storage",
        "service_offering",
        "business_service",
        "technical_service",
        "custom",
      ],
      required: true,
      index: true,
    },
    sourceId: { type: Schema.Types.ObjectId, required: true, index: true },
    targetType: {
      type: String,
      enum: [
        "ci",
        "service",
        "application",
        "database",
        "server",
        "network",
        "storage",
        "service_offering",
        "business_service",
        "technical_service",
        "custom",
      ],
      required: true,
      index: true,
    },
    targetId: { type: Schema.Types.ObjectId, required: true, index: true },
    dependencyType: {
      type: String,
      enum: [
        "depends_on",
        "requires",
        "provides",
        "hosts",
        "connects_to",
        "interfaces_with",
        "backs_up",
        "replicates_to",
        "monitors",
        "manages",
        "routes_to",
        "shares_data_with",
      ],
      default: "depends_on",
      index: true,
    },
    criticality: {
      type: String,
      enum: ["critical", "high", "medium", "low"],
      default: "medium",
      index: true,
    },
    impactType: {
      type: String,
      enum: [
        "outage",
        "degraded_performance",
        "data_loss",
        "security_risk",
        "compliance_risk",
        "capacity_constraint",
        "custom",
      ],
      default: "degraded_performance",
    },
    isActive: { type: Boolean, default: true, index: true },
    isBidirectional: { type: Boolean, default: false },
    autoDiscovered: { type: Boolean, default: false },
    discoverySource: { type: String, trim: true, default: "" },
    validationStatus: {
      type: String,
      enum: ["unvalidated", "validated", "invalid", "stale"],
      default: "unvalidated",
      index: true,
    },
    lastValidatedAt: { type: Date },
    validatedBy: { type: Schema.Types.ObjectId, ref: "User" },
    metadata: { type: Schema.Types.Mixed, default: {} },
    createdBy: { type: Schema.Types.ObjectId, ref: "User" },
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date },
    deletedBy: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true },
);
DependencySchema.index({
  tenantId: 1,
  sourceType: 1,
  sourceId: 1,
  isDeleted: 1,
});
DependencySchema.index({
  tenantId: 1,
  targetType: 1,
  targetId: 1,
  isDeleted: 1,
});
DependencySchema.index({ tenantId: 1, dependencyType: 1, criticality: 1 });
module.exports = model("Dependency", DependencySchema);
