const { Schema, model } = require('mongoose');
const ImprovementInitiativeSchema = new Schema({
  tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
  number: { type: String, required: true, unique: true },
  title: { type: String, required: true, trim: true },
  description: { type: String, trim: true, default: '' },
  opportunityId: { type: Schema.Types.ObjectId, ref: 'ImprovementOpportunity', index: true },
  status: { type: String, enum: ['planned', 'approved', 'in_progress', 'on_hold', 'review', 'completed', 'cancelled', 'deferred'], default: 'planned', index: true },
  priority: { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'medium' },
  type: { type: String, enum: ['process_improvement', 'technology_upgrade', 'training', 'policy_change', 'automation', 'cost_reduction', 'quality_improvement', 'compliance', 'other'], default: 'process_improvement' },
  startDate: { type: Date },
  endDate: { type: Date },
  plannedStartDate: { type: Date },
  plannedEndDate: { type: Date },
  actualStartDate: { type: Date },
  actualEndDate: { type: Date },
  sponsorId: { type: Schema.Types.ObjectId, ref: 'User', index: true },
  ownerId: { type: Schema.Types.ObjectId, ref: 'User', index: true },
  teamId: { type: Schema.Types.ObjectId, ref: 'Team' },
  budget: { type: Number, default: 0 },
  currency: { type: String, default: 'USD' },
  actualCost: { type: Number, default: 0 },
  baselineMetrics: [{
    metricName: { type: String },
    baselineValue: { type: Number },
    unit: { type: String },
    measuredAt: { type: Date },
    source: { type: String },
  }],
  targetMetrics: [{
    metricName: { type: String },
    targetValue: { type: Number },
    unit: { type: String },
    targetDate: { type: Date },
    currentValue: { type: Number },
    lastMeasuredAt: { type: Date },
  }],
  benefits: [{
    name: { type: String },
    description: { type: String },
    type: { type: String, enum: ['financial', 'efficiency', 'quality', 'customer_satisfaction', 'risk_reduction', 'compliance', 'employee_satisfaction', 'other'] },
    estimatedValue: { type: Number },
    actualValue: { type: Number },
    unit: { type: String },
    realizationDate: { type: Date },
  }],
  costs: [{
    category: { type: String, enum: ['labor', 'technology', 'training', 'consulting', 'materials', 'licenses', 'infrastructure', 'other'] },
    plannedAmount: { type: Number },
    actualAmount: { type: Number },
    currency: { type: String, default: 'USD' },
    incurredAt: { type: Date },
    description: { type: String },
  }],
  risks: [{
    description: { type: String },
    probability: { type: String, enum: ['low', 'medium', 'high'] },
    impact: { type: String, enum: ['low', 'medium', 'high', 'critical'] },
    mitigation: { type: String },
    ownerId: { type: Schema.Types.ObjectId, ref: 'User' },
  }],
  metadata: { type: Schema.Types.Mixed, default: {} },
  createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
  isDeleted: { type: Boolean, default: false },
  deletedAt: { type: Date },
  deletedBy: { type: Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });
ImprovementInitiativeSchema.index({ tenantId: 1, status: 1, isDeleted: 1 });
ImprovementInitiativeSchema.index({ tenantId: 1, sponsorId: 1, ownerId: 1 });
ImprovementInitiativeSchema.index({ tenantId: 1, opportunityId: 1 });
module.exports = model('ImprovementInitiative', ImprovementInitiativeSchema);
