const { Schema, model } = require('mongoose');
const ReleaseDeploymentSchema = new Schema({
  tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
  releaseId: { type: Schema.Types.ObjectId, ref: 'Release', required: true, index: true },
  name: { type: String, required: true, trim: true },
  number: { type: String, required: true, unique: true },
  environment: { type: String, enum: ['development', 'test', 'staging', 'production', 'dr'], required: true, index: true },
  status: { type: String, enum: ['scheduled', 'in_progress', 'completed', 'failed', 'rolled_back', 'cancelled'], default: 'scheduled', index: true },
  deploymentType: { type: String, enum: ['full', 'incremental', 'hotfix', 'rollback', 'canary', 'blue_green'], default: 'full' },
  rolloutPercentage: { type: Number, default: 100 },
  strategy: { type: String, enum: ['big_bang', 'phased', 'canary', 'blue_green', 'rolling'], default: 'phased' },
  scheduledAt: { type: Date },
  startedAt: { type: Date },
  completedAt: { type: Date },
  deployedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  deployedComponents: [{
    componentId: { type: Schema.Types.ObjectId, ref: 'ReleaseComponent' },
    version: { type: String },
    status: { type: String, enum: ['pending', 'deploying', 'deployed', 'failed', 'rolled_back'], default: 'pending' },
    deployedAt: { type: Date },
    deployedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    rollbackVersion: { type: String },
    healthCheckStatus: { type: String, enum: ['pending', 'passed', 'failed'], default: 'pending' },
    healthCheckUrl: { type: String },
    healthCheckResult: { type: Schema.Types.Mixed },
  }],
  preDeploymentChecks: [{
    name: { type: String },
    description: { type: String },
    status: { type: String, enum: ['pending', 'passed', 'failed', 'skipped'], default: 'pending' },
    result: { type: String },
    checkedAt: { type: Date },
    checkedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  }],
  postDeploymentChecks: [{
    name: { type: String },
    description: { type: String },
    status: { type: String, enum: ['pending', 'passed', 'failed', 'skipped'], default: 'pending' },
    result: { type: String },
    checkedAt: { type: Date },
    checkedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  }],
  rollbackDeploymentId: { type: Schema.Types.ObjectId, ref: 'ReleaseDeployment' },
  rollbackReason: { type: String, trim: true, default: '' },
  rollbackInitiatedAt: { type: Date },
  rollbackInitiatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  metadata: { type: Schema.Types.Mixed, default: {} },
  createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
  isDeleted: { type: Boolean, default: false },
  deletedAt: { type: Date },
  deletedBy: { type: Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });
ReleaseDeploymentSchema.index({ tenantId: 1, releaseId: 1, environment: 1, status: 1 });
ReleaseDeploymentSchema.index({ tenantId: 1, environment: 1, status: 1 });
module.exports = model('ReleaseDeployment', ReleaseDeploymentSchema);
